pxe:
  image: amosbird/pxe
  net: host
  cap_add:
    - NET_ADMIN
  volumes:
    - ./dnsmasq.conf:/etc/dnsmasq.d/dnsmasq.conf
    - ./tftpboot:/tftpboot
  restart: always

web:
  image: nginx:alpine
  net: host
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./tftpboot:/var/lib/nginx/html
  restart: always
